[project]
name = "finance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "camelot-py>=1.0.9",
    "jupyterlab>=4.4.5",
    "pymupdf>=1.26.3",
    "tabula-py>=2.10.0",
]
